---
#--------------------------------
# Playbook の基本的な構造
#--------------------------------
# ---                          # playbook 開始を示す
# - name: Play の説明          # Playbookの1区切り(配列)をPlayと呼ぶ
#   hosts: localhost　　　　　　# 対象のホストを指定
#   tasks:                     # 実際に行う処理を追記
#     - name: タスク1           
#       ansible.builtin.command: ...
#     - name: タスク2
#       ansible.builtin.debug: ...

#--------------------------------
# 補足
#--------------------------------
#   ansible.builtin.{モジュール名}
#   -> Ansibleの標準モジュールを呼び出して使用する
#      モジュール名は、ansible-doc コマンドで確認できる
#       例) ansible-doc -l | grep {モジュール名}
#       例) ansible-doc -s {モジュール名} ※ よく使う、ひな形を表示
#
#   register: 変数名
#   -> タスクの実行結果を変数に格納する
# 
#   changed_when: false
#   -> タスクによってサーバーの状態が変更されたか？を記録する変数
#      確認・表示だけのタスクは、状態変更しないため、明示的に false を格納
#
#   gather_facts: false
#   -> ホスト情報収集の有無(OS, CPUなど)を無効化

#--------------------------------
# Playbook
#--------------------------------
- name: multipass 疎通確認
  hosts: localhost
  connection: local   # VMにSSHせず、ローカルで実行
  gather_facts: false # ホスト情報収集の有無(OS, CPUなど)を無効化
  tasks:

    - name: 稼働中の VM 一覧を JSON 形式で取得
      ansible.builtin.command: "{{ mp_cmd }} list --format json"
      register: mp_list_json
      changed_when: false

    - name: 既存の VM 名の一覧を作成
      ansible.builtin.set_fact:
        mp_existing_names: "{{ (mp_list_json.stdout | from_json).list | map(attribute='name') | list }}"
      changed_when: false

    - name: デバッグ
      ansible.builtin.debug:
        var: mp_existing_names